language: csharp
mono: none
dotnet: 2.0.0
dist: trusty

env:
  global:
    - CONFIGURATION=Release

script:
  - dotnet restore
  - dotnet test ./test/Axe.SimpleHttpMock.Test/Axe.SimpleHttpMock.Test.csproj -f netcoreapp2.0
