language: csharp
solution: Axe.SimpleHttpMock.sln

env:
  global:
    - CONFIGURATION=Release

matrix:
  include:
    - os: linux
      dist: trusty # Ubuntu 14.04
      dotnet: 1.0.1
      mono: none
      env: DOTNETCORE=1
      sudo: required

script: ./travis_build_and_test.sh
